/*
 * This source file was generated by the Gradle 'init' task
 */
package org.trueaim;

import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.system.MemoryUtil.*;

public class App {
    public static void main(String[] args) {
        if (!glfwInit()) {
            throw new IllegalStateException("Unable to initialize GLFW");
        }

        long window = glfwCreateWindow(800, 600, "Test", NULL, NULL);
        glfwMakeContextCurrent(window);
        glfwShowWindow(window);

        while (!glfwWindowShouldClose(window)) {
            glfwSwapBuffers(window); // show rendered frame
            glfwPollEvents();        // process inputs
        }


        glfwDestroyWindow(window);
        glfwTerminate();
    }
}
